from .binary_cross_entropy import BinaryCrossEntropy
from .quadratic_cost import QuadraticCost
from .categorial_cross_entropy import CategorialCrossEntropy
from .mean_absolute_cost import MeanAbsoluteCost